# Generated by Django 5.1.6 on 2025-09-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_initial'),
        ('core', '0002_delete_onlinemedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onlinemedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='icons')),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('specialties', models.ManyToManyField(blank=True, related_name='core_online_specialties', to='Doctor.specialty')),
            ],
        ),
    ]
