# Generated by Django 5.2.6 on 2025-09-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_onlinemedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='icons')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalcentertype')),
            ],
        ),
    ]
