# Generated by Django 5.2.6 on 2025-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_alter_doctorrating_doctor_alter_doctorrating_score_and_more'),
        ('core', '0004_medical_centers'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms_and_disease',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='Doctor.specialty'),
        ),
    ]
