from .doctor_views import *
from .specialty_views import *
from .service_views import *
from .insurance_views import *
from .appoitment_views import *
from .city_views import *
from .clinic_views import *
from .paraclinic_views import *
from .pharmacy_views import *
from .labsp_views import *
from .review_views import *
from .online_views import *
from .khadamat_views import *
from .pishnahad_views import *
from .pishnahad_img_views import *
from .phone_appointment_views import *
from .text_appointment_views import *
from .patient_info_views import *
from .FAQ_views import *
from .user_views import *
from .userotp_views import *
from .wallet_views import *
from .doctor_register_views import *
from .type_views import *
from .post_views import *
from .social_link_views import *
from .blog_faq_views import *
from .medical_center_type_views import *
from .most_visited_views import *
from .sympots_views import *
from .doctorto_specialty_views import *
from .center_for_diagnosis_views import *
from .latest_medical_views import *
from .top_clinic_views import *
from .city_lab_views import *
from .comment_views import *
from .women_sympots_views import *
from .online_medical_views import *
from .dashboard import *
from .admin_login import *
from .admin_logout import *
from .labratory_views import *



