# Generated by Django 5.1.6 on 2025-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تخصص')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediacal_code', models.CharField(max_length=20, verbose_name='کد نظام پزشکی')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('full_name_en', models.CharField(max_length=60, verbose_name='نام کامل به انگلیسی')),
                ('national_id', models.CharField(max_length=10, verbose_name='کدملی')),
                ('email_address', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('famale', 'زن'), ('other', 'غیره')], max_length=10, verbose_name='جنسیت')),
                ('specialties', models.ManyToManyField(to='accounts.specialty', verbose_name='تخصص')),
            ],
        ),
    ]
