# Generated by Django 5.2.6 on 2025-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userotp_phone_number_alter_userotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
