# Generated by Django 5.2.6 on 2025-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fix_missing_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='code',
            field=models.CharField(default='123456'),
        ),
    ]
