# Generated by Django 5.2.6 on 2025-10-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_managers_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('doctor', 'Doctor')], max_length=10, null=True),
        ),
    ]
