# Generated by Django 5.2.6 on 2025-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'مدیرکل'), ('admin', 'مدیر'), ('staff', 'کارمند'), ('doctor', 'دکتر')], default='doctor', max_length=20),
        ),
    ]
