# Generated by Django 5.2.6 on 2025-10-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctor_register',
        ),
    ]
