# Generated by Django 5.2.6 on 2025-09-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
