# Generated by Django 5.2.6 on 2025-09-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
