# Generated by Django 5.2.6 on 2025-10-02 08:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0027_remove_phone_appointment_user_and_more'),
        ('blog', '0006_alter_post_title_alter_type_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('youtube', 'یوتیوب'), ('aparat', 'آپارات'), ('website', 'وب\u200cسایت')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(help_text='آدرس لینک شبکه اجتماعی')),
                ('icon', models.ImageField(blank=True, help_text='آیکن دلخواه (اختیاری)', null=True, upload_to='icons')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='Doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
