# Generated by Django 5.1.6 on 2025-09-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.topclinics'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='core.symptoms_and_disease'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(related_name='clinics', to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='Doctor.insurance'),
        ),
        migrations.AddField(
            model_name='onlinemedicalconsultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_consultations', to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='onlines',
            field=models.ManyToManyField(blank=True, related_name='doctor_online_specialties', to='Doctor.onlinemedicalconsultation'),
        ),
        migrations.AddField(
            model_name='paraclinicservices',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.city'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.city'),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.city'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, to='Doctor.service'),
        ),
        migrations.AddField(
            model_name='onlinemedicalconsultation',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctor.specialty'),
        ),
    ]
