# Generated by Django 5.1.6 on 2025-09-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='onlines',
        ),
    ]
