# Generated by Django 5.1.6 on 2025-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_alter_doctor_image_labratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labratory',
            name='specialty',
        ),
        migrations.AddField(
            model_name='labratory',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, to='Doctor.specialty'),
        ),
    ]
