# Generated by Django 5.1.6 on 2025-09-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_remove_labratory_specialty_labratory_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labratory',
            name='specialty',
        ),
        migrations.AddField(
            model_name='labratory',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
