# Generated by Django 5.1.6 on 2025-09-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_remove_labratory_specialty_labratory_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
