# Generated by Django 5.1.6 on 2025-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_remove_labratory_specialty_labratory_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='labratory',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labratory',
            name='insurance',
            field=models.ManyToManyField(blank=True, null=True, to='Doctor.insurance'),
        ),
    ]
