# Generated by Django 5.1.6 on 2025-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_labratory_address_labratory_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labratory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
