# Generated by Django 5.1.6 on 2025-09-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0012_labratory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='khadamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('zir_goroh', models.ManyToManyField(blank=True, null=True, to='Doctor.service')),
            ],
        ),
    ]
