# Generated by Django 5.1.6 on 2025-09-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0014_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pishnahad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pishnahad_ha', to='Doctor.doctor')),
                ('khadamat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pishnahad_ha', to='Doctor.khadamat')),
            ],
        ),
        migrations.CreateModel(
            name='PishnahadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pishnahad/')),
                ('pishnahad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Doctor.pishnahad')),
            ],
        ),
    ]
