# Generated by Django 5.1.6 on 2025-09-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0015_pishnahad_pishnahadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
    ]
