# Generated by Django 5.1.6 on 2025-09-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_appoinments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appoinments',
            name='start_time',
        ),
    ]
