# Generated by Django 5.2.6 on 2025-09-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_remove_appoinments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labratory',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
