# Generated by Django 5.2.6 on 2025-09-19 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0020_appointment_patientinfo_delete_appoinments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='doctor',
            name='success_appointments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='khadamat',
            name='zir_goroh',
            field=models.ManyToManyField(blank=True, to='Doctor.service'),
        ),
        migrations.AlterField(
            model_name='labratory',
            name='insurance',
            field=models.ManyToManyField(blank=True, to='Doctor.insurance'),
        ),
        migrations.AlterField(
            model_name='labratory',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='Doctor.lab_specialty'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.appointment'),
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('doctor', 'user')},
            },
        ),
    ]
