# Generated by Django 5.2.6 on 2025-09-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0022_alter_doctorrating_doctor_alter_doctorrating_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(null=True, to='Doctor.specialty'),
        ),
    ]
