# Generated by Django 5.2.6 on 2025-09-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0026_phone_appointment_text_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='text_appointment',
            name='user',
        ),
    ]
