# Generated by Django 5.2.6 on 2025-10-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0027_remove_phone_appointment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
