# Generated by Django 5.2.6 on 2025-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0028_doctor_date_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
