# Generated by Django 5.2.6 on 2025-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0029_doctor_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
