# Generated by Django 5.2.6 on 2025-10-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0030_remove_doctor_rating_doctor_medical_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.PositiveSmallIntegerField(default=0)),
                ('recommend', models.BooleanField(default=True)),
                ('behavior', models.PositiveSmallIntegerField(default=0)),
                ('explain', models.PositiveSmallIntegerField(default=0)),
                ('skill', models.PositiveSmallIntegerField(default=0)),
                ('reception', models.PositiveSmallIntegerField(default=0)),
                ('environment', models.PositiveSmallIntegerField(default=0)),
                ('wait_time', models.CharField(blank=True, choices=[('0-15', '۰-۱۵ دقیقه'), ('15-45', '۱۵-۴۵ دقیقه'), ('45-90', '۴۵-۹۰ دقیقه'), ('90+', 'بیش از ۹۰ دقیقه')], max_length=20, null=True)),
                ('reason', models.CharField(blank=True, choices=[('checkup', 'ویزیت چکاپ عمومی'), ('followup', 'ویزیت پیگیری'), ('treatment', 'درمان خاص'), ('other', 'سایر موارد')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Doctor.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
